// src/pages/Dashboard.tsx

import React from 'react';
import { ServiceCard } from '@/components/Dashboard/ServiceCard';
import { QuickActions } from '@/components/Dashboard/QuickActions';
import { RecentActivity } from '@/components/Dashboard/RecentActivity';
import { 
  GitBranch, 
  Container, 
  Zap, 
  Server, 
  Database
} from 'lucide-react';

interface DashboardProps {
  containerSize?: string;
}

export const Dashboard: React.FC<DashboardProps> = ({ containerSize }) => {
  const isCompact = containerSize === 'compact';
  const isMedium = containerSize === 'medium';
  
  const services = [
    {
      title: 'GitLab',
      description: 'Version control & CI/CD',
      icon: GitBranch,
      status: 'online' as const,
      color: 'orange',
      metrics: [
        { label: 'Active MRs', value: '12' },
        { label: 'Pipelines', value: '3' },
      ],
      actions: [
        { label: 'New MR', onClick: () => console.log('New MR') },
        { label: 'View Pipelines', onClick: () => console.log('View Pipelines') },
      ],
    },
    {
      title: 'Docker',
      description: 'Container management',
      icon: Container,
      status: 'online' as const,
      color: 'cyan',
      metrics: [
        { label: 'Running', value: '8' },
        { label: 'Images', value: '24' },
      ],
      actions: [
        { label: 'View Containers', onClick: () => console.log('View Containers') },
        { label: 'Build Image', onClick: () => console.log('Build Image') },
      ],
    },
    {
      title: 'API Testing',
      description: 'REST & GraphQL testing',
      icon: Zap,
      status: 'online' as const,
      color: 'green',
      metrics: [
        { label: 'Collections', value: '15' },
        { label: 'Tests Run', value: '342' },
      ],
      actions: [
        { label: 'New Request', onClick: () => console.log('New Request') },
        { label: 'Run Collection', onClick: () => console.log('Run Collection') },
      ],
    },
    {
      title: 'Servers',
      description: 'Infrastructure monitoring',
      icon: Server,
      status: 'warning' as const,
      color: 'purple',
      metrics: [
        { label: 'Online', value: '4/5' },
        { label: 'Load Avg', value: '0.8' },
      ],
      actions: [
        { label: 'View Logs', onClick: () => console.log('View Logs') },
        { label: 'SSH Connect', onClick: () => console.log('SSH Connect') },
      ],
    },
    {
      title: 'AI-DB',
      description: 'Database & AI services',
      icon: Database,
      status: 'online' as const,
      color: 'pink',
      metrics: [
        { label: 'Connections', value: '23' },
        { label: 'Queries/min', value: '156' },
      ],
      actions: [
        { label: 'Query Builder', onClick: () => console.log('Query Builder') },
        { label: 'AI Assistant', onClick: () => console.log('AI Assistant') },
      ],
    },
  ];

  return (
    <div className={`space-y-${isCompact ? '3' : '6'} ${isCompact ? 'p-3' : 'p-6'}`}>
      {/* Header */}
      <div>
        <h1 className={`font-bold text-white mb-2 ${isCompact ? 'text-xl' : 'text-3xl'}`}>
          DevOps Dashboard
        </h1>
        <p className={`text-gray-400 ${isCompact ? 'text-sm' : ''}`}>
          {isCompact ? 'DevOps workflow management' : 'Manage your development workflow from a single interface'}
        </p>
      </div>

      {/* Quick Actions */}
      <QuickActions containerSize={containerSize} />

      {/* Services Grid */}
      <div className={`grid gap-${isCompact ? '3' : '6'} ${
        isCompact 
          ? 'grid-cols-1' 
          : isMedium 
            ? 'grid-cols-1 md:grid-cols-2' 
            : 'grid-cols-1 md:grid-cols-2 xl:grid-cols-3'
      }`}>
        {services.map((service, index) => (
          <ServiceCard key={index} {...service} containerSize={containerSize} />
        ))}
      </div>

      {/* Recent Activity */}
      {!isCompact && <RecentActivity containerSize={containerSize} />}
    </div>
  );
};

// codebridge-angular/src/app/features/dashboard/dashboard.component.ts
import { Component, Input } from '@angular/core';

interface ServiceData {
  title: string;
  description: string;
  icon: string;
  status: 'online' | 'offline' | 'warning';
  color: string;
  metrics: { label: string; value: string }[];
  actions: { label: string; action: string }[];
}

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent {
  @Input() containerSize: 'compact' | 'medium' | 'normal' = 'normal';

  services: ServiceData[] = [
    {
      title: 'GitLab',
      description: 'Version control & CI/CD',
      icon: 'git-branch',
      status: 'online',
      color: 'orange',
      metrics: [
        { label: 'Active MRs', value: '12' },
        { label: 'Pipelines', value: '3' }
      ],
      actions: [
        { label: 'New MR', action: 'new-mr' },
        { label: 'View Pipelines', action: 'view-pipelines' }
      ]
    },
    {
      title: 'Docker',
      description: 'Container management',
      icon: 'container',
      status: 'online',
      color: 'cyan',
      metrics: [
        { label: 'Running', value: '8' },
        { label: 'Images', value: '24' }
      ],
      actions: [
        { label: 'View Containers', action: 'view-containers' },
        { label: 'Build Image', action: 'build-image' }
      ]
    },
    {
      title: 'API Testing',
      description: 'REST & GraphQL testing',
      icon: 'zap',
      status: 'online',
      color: 'green',
      metrics: [
        { label: 'Collections', value: '15' },
        { label: 'Tests Run', value: '342' }
      ],
      actions: [
        { label: 'New Request', action: 'new-request' },
        { label: 'Run Collection', action: 'run-collection' }
      ]
    },
    {
      title: 'Servers',
      description: 'Infrastructure monitoring',
      icon: 'server',
      status: 'warning',
      color: 'purple',
      metrics: [
        { label: 'Online', value: '4/5' },
        { label: 'Load Avg', value: '0.8' }
      ],
      actions: [
        { label: 'View Logs', action: 'view-logs' },
        { label: 'SSH Connect', action: 'ssh-connect' }
      ]
    },
    {
      title: 'AI-DB',
      description: 'Database & AI services',
      icon: 'database',
      status: 'online',
      color: 'pink',
      metrics: [
        { label: 'Connections', value: '23' },
        { label: 'Queries/min', value: '156' }
      ],
      actions: [
        { label: 'Query Builder', action: 'query-builder' },
        { label: 'AI Assistant', action: 'ai-assistant' }
      ]
    }
  ];

  getGridClass(): string {
    switch (this.containerSize) {
      case 'compact':
        return 'grid-compact';
      case 'medium':
        return 'grid-medium';
      default:
        return 'grid-normal';
    }
  }

  handleQuickAction(action: string) {
    console.log('Quick action:', action);
    // Implement quick action handling
  }

  handleServiceAction(action: string) {
    console.log('Service action:', action);
    // Implement service action handling
  }
}
<div class="dashboard-container" [class]="'container-' + containerSize">
  <!-- Header -->
  <div class="dashboard-header">
    <h1 class="title">DevOps Dashboard</h1>
    <p class="subtitle">
      {{ containerSize === 'compact' ? 'DevOps workflow management' : 'Manage your development workflow from a single interface' }}
    </p>
  </div>

  <!-- Quick Actions -->
  <div class="quick-actions-section">
    <app-quick-actions 
      [containerSize]="containerSize"
      (actionClick)="handleQuickAction($event)">
    </app-quick-actions>
  </div>

  <!-- Services Grid -->
  <div class="services-grid" [class]="getGridClass()">
    <app-service-card 
      *ngFor="let service of services"
      [service]="service"
      [containerSize]="containerSize"
      (actionClick)="handleServiceAction($event)">
    </app-service-card>
  </div>

  <!-- Recent Activity -->
  <div class="recent-activity-section" *ngIf="containerSize !== 'compact'">
    <app-recent-activity [containerSize]="containerSize"></app-recent-activity>
  </div>
</div>
